/*
 * generated by Xtext
 */
package fr.enseeiht;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PETRI1RuntimeModule extends fr.enseeiht.AbstractPETRI1RuntimeModule {

}
