/*
 * generated by Xtext
 */
package fr.enseeiht.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PETRI1UiModule extends fr.enseeiht.ui.AbstractPETRI1UiModule {
	public PETRI1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
