/*
* generated by Xtext
*/
package fr.enseeiht.ui.contentassist;

import fr.enseeiht.ui.contentassist.AbstractPETRI1ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PETRI1ProposalProvider extends AbstractPETRI1ProposalProvider {

}
