/*
* generated by Xtext
*/
package fr.enseeiht;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PETRI1UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.enseeiht.ui.internal.PETRI1Activator.getInstance().getInjector("fr.enseeiht.PETRI1");
	}
	
}
